AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  gokul-sam-url

  Sample SAM Template for gokul-sam-url

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    
Resources:
  UrlShortenerTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: UrlShortener-JCG
      AttributeDefinitions:
        - AttributeName: "short_code"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "short_code"
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  MyHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: prod
      CorsConfiguration:
        AllowOrigins:
          - '*'
        AllowHeaders:
          - Content-Type
        AllowMethods:
          - GET
          - POST
          - OPTIONS
  UrlShortener:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: url-shortener/
      Handler: app.lambdaHandler
      Runtime: nodejs22.x
      Architectures:
      - x86_64
      Events:
        Redirect:
          Type: HttpApi # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            ApiId: !Ref MyHttpApi
            Path: /{shortCode}
            Method: get
        Shortener:
          Type: HttpApi # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            ApiId: !Ref MyHttpApi
            Path: /shortener
            Method: post
      Policies:
        - DynamoDBCrudPolicy:
            TableName: UrlShortener-JCG
      Environment:
        Variables:
          TABLE_NAME: !Ref UrlShortenerTable
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
        - app.ts
